- name:
  hosts: hq_host
  become: yes
  vars:
    NODE_EXPORTER_PATH: "/opt/node_exporter"
    NODE_EXPORTER_EXEC_PATH: "{{ NODE_EXPORTER_PATH }}/node_exporter-1.9.0.linux-amd64/node_exporter"
  tasks:
    - name: check dir
      file:
        path: "{{ NODE_EXPORTER_PATH }}"
        state: directory
        owner: root
        group: root
        mode: "0770"
      tags: dir_check
    
    - name: download node-expoter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz"
        dest: "{{ NODE_EXPORTER_PATH }}"
        owner: root
        group: root
        mode: "0770"

    - name: unzip node-exporter
      unarchive:
        src: "{{ NODE_EXPORTER_PATH }}/node_exporter-1.9.0.linux-amd64.tar.gz"
        dest: "{{ NODE_EXPORTER_PATH }}"
        owner: root
        group: root
        mode: "0770"
        remote_src: yes
      tags: unzip

    - name: config systemd
      template: 
        src: "templates/node-exporter.service.j2"
        dest: "/etc/systemd/system/node-exporter.service"
        owner: root
        group: root
        mode: "0770"
      tags: copy-config

    - name: systemd
      systemd:
        name: node-exporter.service
        daemon_reload: yes
      tags: systemd

    - name: systemd
      systemd:
        name: node-exporter.service
        state: started
        enabled: yes
      tags: systemd
