- name: Install Node Exporter on all hosts
  hosts: all
  become: yes
  vars:
    NODE_EXPORTER_PATH: "/opt/node_exporter"
    NODE_EXPORTER_EXEC_PATH: "{{ NODE_EXPORTER_PATH }}/node_exporter-1.9.0.linux-amd64/node_exporter"
  tasks:
    - name: create the desired path to download files
      file:
        path: "{{ NODE_EXPORTER_PATH }}"
        state: directory
        owner: root
        group: root
        mode: "0770"
      tags: dir-check
    
    - name: download node-expoter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz"
        dest: "{{ NODE_EXPORTER_PATH }}"
        owner: root
        group: root
        mode: "0770"
      tags: download

    - name: unzip node-exporter
      unarchive:
        src: "{{ NODE_EXPORTER_PATH }}/node_exporter-1.9.0.linux-amd64.tar.gz"
        dest: "{{ NODE_EXPORTER_PATH }}"
        owner: root
        group: root
        mode: "0770"
        remote_src: yes
      tags: unzip-files

    - name: copy systemd service file to /etc/systemd/system/
      template: 
        src: "templates/node-exporter.service.j2"
        dest: "/etc/systemd/system/node-exporter.service"
        owner: root
        group: root
        mode: "0770"
      tags: systemd

    - name: systemd daemon-reload
      systemd:
        name: node-exporter.service
        daemon_reload: yes
      tags: systemd

    - name: systemd-service start
      systemd:
        name: node-exporter.service
        state: started
        enabled: yes
      tags: systemd
