- name:
  hosts: master-monitor
  become: yes
  vars:
    PROMETHEUS_INSTALL_PATH: "/opt/prometheus"
  tasks:
    - name:
      snap:
        name: grafana
      tags: snap-install

    - name:
      snap:
        name: grafana
        state: started
        enabled: yes
      tags: snap-service

    - name: create if not exists
      file:
        path: "{{ PROMETHEUS_INSTALL_PATH }}"
        state: directory
        owner: root
        group: root
        mode: "0770"
      
    - name: prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.53.4/prometheus-2.53.4.linux-amd64.tar.gz"
        dest: "{{ PROMETHEUS_INSTALL_PATH }}/"
        owner: root
        group: root
        mode: "0770"
      tags: dl

    - name: unzip
      unarchive:
        src: "{{ PROMETHEUS_INSTALL_PATH }}/prometheus-2.53.4.linux-amd64.tar.gz"
        dest: "{{ PROMETHEUS_INSTALL_PATH }}/"
        owner: root
        group: root
        mode: "0770"
      tags: unzip

    # - name: config

    # - name: start prometheus
      # shell: 
