- name:
  hosts: hq_host
  become: yes
  vars:
    PROMETHEUS_INSTALL_PATH: "/opt/prometheus"
    PROMETHEUS_CONFIG_PATH: "{{ PROMETHEUS_INSTALL_PATH }}/prometheus-2.53.4.linux-amd64/prom_config.yml"
    PROMETHEUS_EXEC_PATH: "{{ PROMETHEUS_INSTALL_PATH }}/prometheus-2.53.4.linux-amd64/prometheus"
  tasks:
    - name: install grafana with snap
      snap:
        name: grafana
      tags: snap-install

    - name: enable grafana snap service
      snap:
        name: grafana
        state: present
      tags: snap-service

    - name: create directory to dl prometheus
      file:
        path: "{{ PROMETHEUS_INSTALL_PATH }}"
        state: directory
        owner: root
        group: root
        mode: "0770"
      tags: create-dir
      
    - name: download prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.53.4/prometheus-2.53.4.linux-amd64.tar.gz"
        dest: "{{ PROMETHEUS_INSTALL_PATH }}/"
        owner: root
        group: root
        mode: "0770"
      tags: download

    - name: unzip prometheus
      unarchive:
        src: "{{ PROMETHEUS_INSTALL_PATH }}/prometheus-2.53.4.linux-amd64.tar.gz"
        dest: "{{ PROMETHEUS_INSTALL_PATH }}/"
        owner: root
        group: root
        mode: "0770"
      tags: unzip

    - name: copy prometheus config
      copy:
        src: "templates/prom_config.yml"
        dest: "{{ PROMETHEUS_CONFIG_PATH }}"
        owner: root
        group: root
        mode: "0770"
      tags: copy-prom-conf

    - name: copy prometheus systemd service file
      template: 
        src: "templates/prometheus.service.j2"
        dest: "/etc/systemd/system/prometheus.service"
        owner: root
        group: root
        mode: "0770"
      tags: systemd

    - name: systemd daemon-reload
      systemd:
        name: prometheus.service
        daemon_reload: yes
      tags: systemd

    - name: enable prometheus systemd service
      systemd:
        name: prometheus.service
        state: started
        enabled: yes
      tags: systemd
