---
- name: Install and config MySQL @ localhost, quadzero
  hosts: mysql_servers
  become: yes
  vars_files:
    - vault/mysql_secrets.yml
  vars:
    mysql_bind_address: "0.0.0.0"
    mysql_databases:
        - name: "test_db"
    
  tasks:
    - name: apt cache update
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: check if service is ok
      service:
        name: mysql.service
        state: started
        enabled: yes
      tags: check_serivce

    - name: install pymysql
      pip:
        name: pymysql
        state: present
      tags: pip

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        login_user: root
        login_password: ""
        state: present
      tags: set_pass
        
    - name: update config file
      template:
        src: templates/my.cnf.j2
        dest: /etc/mysql/my.cnf
      notify: restart mysql service

    - name: create test db
      mysql_db:
        name: "{{ item.name }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present
      loop: "{{ mysql_databases }}"

  handlers:
    - name: restart mysql service
      service:
        name: mysql
        state: present
